version: '3.8'

services:
  postgres:
    image: postgres:14.10-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  constru-control:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: constru-control
    ports:
      - '${APP_PORT:-8000}:8000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
